apiVersion: v1
kind: Pod        # ← Still Pod (not multicontainer)
metadata:
   name: multicontainer
   namespace: roboshop
   labels:
     purpose: multicontainer
spec:
  containers:
  - name: nginx                   # Main app (web server)
    image: nginx
  - name: almalinux               # Sidecar (helper)
    image: almalinux:9
    command: ["sleep", "1000"]    # Keeps alive forever