apiVersion: v1
kind: Pod
metadata:
   name: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
    # soft limit
     requests:       # ← THE RESERVATION (Min needed)
     memory: "68Mi"
     cpu: "100m"     # 1/10th of a CPU core
     # hard limit 
     limits:         # ← THE CEILING (Max allowed)
        memory: "100Mi"
        cpu: "120m"