apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:          # Bucket 1: The Reservation
        memory: "68Mi"
        cpu: "100m"
      limits:            # Bucket 2: The Ceiling
        memory: "100Mi"
        cpu: "120m"