apiVersion: v1
kind: Pod
metadata:
  name: service-demo
  labels:                           # ← SAME LABELS AS 04!
    project: roboshop
    component: frontend
    environment: dev
    purpose: node-port
spec:
  containers:
  - name: nginx
    image: nginx