apiVersion: v1
kind: Pod
metadata:
  name: pod-config-reader
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:                 # ← THE KEY!
    - configMapRef:          # ← Reference the Dictionary
        name: pod-config     # ← From Lab 09